services:     

  opamp-backend:
    container_name: opamp-backend
    build:
      context: ./opamp-backend
      dockerfile: Dockerfile
    ports:
      - 4321:4321
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4321"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - my-network

  otel-collector-with-supervisor:
    container_name: otel-collector-with-supervisor
    build:
      context: ./otel-collector-with-supervisor
      dockerfile: Dockerfile
    depends_on:
      opamp-backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - my-network

  demo-client:
    build:
      dockerfile: Dockerfile
      context: ./client
    restart: always
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector-with-supervisor:4317
      - DEMO_SERVER_ENDPOINT=http://demo-server:7080/hello
    depends_on:
      - demo-server
    networks:
      - my-network

  demo-server:
    build:
      dockerfile: Dockerfile
      context: ./server
    restart: always
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector-with-supervisor:4317
    ports:
      - "7080"
    depends_on:
      - otel-collector-with-supervisor
    networks:
      - my-network           

  oteltui:
    image: ymtdzzz/otel-tui:latest
    container_name: otel-tui
    stdin_open: true
    tty: true
    entrypoint: ["/otel-tui"]
    networks:
      - my-network    

networks:
  my-network:
    driver: bridge