apiVersion: apps/v1
kind: Deployment
metadata:
  name: opamp-backend
  labels:
    app: opamp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opamp-backend
  template:
    metadata:
      labels:
        app: opamp-backend
    spec:
      containers:
        - name: opamp-backend
          image: ghcr.io/keisukesakasai/cndw2024-demo/opamp-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4320
---              
apiVersion: v1
kind: Service
metadata:
  name: opamp-backend
  labels:
    app: opamp-backend
spec:
  selector:
    app: opamp-backend
  ports:
    - protocol: TCP
      port: 4320
      targetPort: 4320
  type: ClusterIP