apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opamp-bridge-binding
subjects:
- kind: ServiceAccount
  name: opamp-bridge-opamp-bridge
  namespace: cndw2024-demo
roleRef:
  kind: ClusterRole
  name: opamp-bridge-role
  apiGroup: rbac.authorization.k8s.io
